TEAM_ID = {'Arsenal': 13,
           'Aston Villa': 24,
           'Atalanta': 300, 
           'Atleti': 63, 
           'B. Dortmund': 44, 
           'Barcelona': 65, 
           'Bayern München': 37, 
           'Benfica': 299, 
           'Bologna': 71, 
           'Brest': 2332, 
           'Celtic': 103, 
           'Club Brugge': 124, 
           'Crvena Zvezda': 579, 
           'Feyenoord': 256, 
           'Girona': 2783, 
           'GNK Dinamo': 684, 
           'Inter': 75, 
           'Juventus': 87,
           'Leipzig': 7614,
           'Leverkusen': 36,
           'Lille': 607,
           'Liverpool': 26,
           'Man City': 167,
           'Milan': 80,
           'Monaco': 248,
           'Paris': 304,
           'PSV': 129,
           'Real Madrid': 52,
           'S. Bratislava': 698,
           'Salzburg': 361,
           'Shakhtar': 1706,
           'Sparta Praha': 354,
           'Sporting CP': 296,
           'Sturm Graz': 390,
           'Stuttgart': 41,
           'Young Boys': 587}